source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HealthKitDemo' do
   platform :ios, '9.0'
   pod 'Firebase/Core'
end

target 'HKDemo' do

end

target 'HKDemo Extension' do
   platform :watchos, '4.3'
end
